### ISSUE TITLE
BUG: can't use `less` in `vineStyle` macro

### ISSUE THREAD

**Issue by Mumujianguang** [vue-vine/vue-vine#138]
writing the code in the vue-vine playground
```ts
import './style.less';

function Home() {
  vineStyle(less`
    .home {
        font-size: 12px;
    }
  `);

  return vine`
    <div class="home">Home</div>
  `;
}
```

got the error below. I can't find the solution to problem in docs of vue-vine
<img width="355" alt="image" src="https://github.com/user-attachments/assets/ffdebb7e-1350-493d-ad2a-ddabbc15673d">

**Comment by ShenQingchuan** [comment]
Would you please share your project on Github or giving some key information like `package.json`, `tsconfig.json` content?

By the way, did you installed less as your `devDependencies`?

**Comment by Mumujianguang** [comment]
> Would you please share your project on Github or giving some key information like `package.json`, `tsconfig.json` content? That would be very useful for us to locate the issue.
> 
> By the way, did you installed less as your `devDependencies`?

yeah, I installed `less`，but the error still exist. the `reproduction` is as below
https://stackblitz.com/edit/github-htajwy?file=src%2Fpages%2Fhome.vine.ts

**Comment by ShenQingchuan** [comment]
Problem resolved, that's because your project's root level `package.json` has declared as `"type": "module"` so that every JS file is interpreted as ESM by default, `require(...)` is not available then.

But we can modify our package exports specification, add a `"node"` spec which target to a CJS file for Node.js to resolve.
