### ISSUE TITLE
Vue Vine fails with current Nuxt version when `ssr` is enabled (default)

### ISSUE THREAD

**Issue by manniL** [vue-vine/vue-vine#163]
Hey all!

See [this reproduction](https://stackblitz.com/edit/vue-vine-163?file=components%2FTest.vine.ts,app.vue,nuxt.config.ts). The app is failing with ` ERROR  [nuxt] [request error] [unhandled] [500] can't access property "accept", __vite_ssr_import_meta__.hot is undefined`.
When disabling SSR via `nuxt.config.ts`, things work fine.

**Comment by ShenQingchuan** [comment]
@manniL Hello Alexander !!

💖 Thanks for your enthusiasm and discovering this bug 🐛

After my researching I found that this problem is caused by some internal issue when we published it in Vue Vine v0.1.18, and `@vue-vine/nuxt-module` is depended on that very low version, which may cause undefined behaviors like what you've met.

I've republished a version `v0.0.2` for `@vue-vine/nuxt-module` and everything seems to work fine 🥳

**Comment by ShenQingchuan** [comment]
The deprecation message has been marked on NPM registry: 

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/ff3c0d94-5f29-4942-ac2d-477fc77ef211">
