### ISSUE TITLE
Problems with using expressions in vcf top-level scope

### ISSUE THREAD

**Issue by baiwusanyu-c** [vue-vine/vue-vine#32]
# Bug reproduce sample

```
const foo = 'foo'
const bar = () => 'bar'
export function App() {
  console.log(foo, bar())
  return vine`
    <div>{{foo}} {{bar()}}</div>
   `
}
```

**Comment by baiwusanyu-c** [comment]
For a simple expression, it can be used or accessed in vcf components, but is currently invalid in templates, because it is compiled into `ctx.foo`

**Comment by ShenQingchuan** [comment]
This is because of we didn't collect valid declarations (without any reactivity API call) on top level into binding metadata for  template compilation.

We must collect them as `VueBindingTypes.LITERAL_CONST` to tell Vue's template compiler remaining them as-is.

I'll fix this in a separate PR and add more details for restrictions of top level declaration.
